### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by tardinha** [symbiote/silverstripe-dynamiclists#24]
Hey,

As an aside, I don't think the permissions are working as expected, as allowing a user access to the Dynamic Lists admin doesn't allow them to edit, create or delete items

Any thoughts?

Cheers

Mark

**Comment by nglasl** [comment]
Oh I bet the name now includes the namespace, so it'll be something like `CMS_ACCESS_Symbiote_DynamicLists_DynamicListAdmin` now.

**Comment by tardinha** [comment]
Yah, it's now Menu-Symbiote-DynamicLists-DynamicListAdmin :)

**Comment by nglasl** [comment]
Any chance you could please throw a PR in @tardinha and tag me on it? Looks like there's 3 occurrences in https://github.com/symbiote/silverstripe-dynamiclists/blob/master/src/dataobjects/DynamicList.php and 3 in https://github.com/symbiote/silverstripe-dynamiclists/blob/master/src/dataobjects/DynamicListItem.php that need changing. I can merge it through and give it a tag.

**Comment by tardinha** [comment]
Doesn't work :P 

Looking at other code, seems things haven't changed:

https://github.com/silverstripe/silverstripe-framework/blob/4/src/Security/Member.php#L1375

**Comment by nglasl** [comment]
Hmm. No worries, I might take a quick peek at this.

**Comment by nglasl** [comment]
It might actually be something more like `CMS_ACCESS_Symbiote-DynamicLists-DynamicListAdmin` or `CMS_ACCESS_Symbiote_DynamicLists_DynamicListAdmin`.

**Comment by nglasl** [comment]
Hey @tardinha, just letting you know I've resolved this and I'm currently putting a PR through.

Turns out it's now `CMS_ACCESS_Symbiote\DynamicLists\DynamicListAdmin`. You can see this by inspecting element on the CMS permissions page, where it says `value="CMS_ACCESS_Symbiote\DynamicLists\DynamicListAdmin"` (just as a heads up for future reference) :smile:

**Comment by nglasl** [comment]
@tardinha all merged in and good to go.
